### ISSUE TITLE
What are the source and victim models used in Tab.7 in the paper?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [Alan-Qin/Transfer_attack_RAP#1]
Hi, we gonna reproduce the result in the paper. However, we don't know exactly what source and victim models used in Tab.7, since there only is one model in each column in Tab.7.

Thanks.

**Comment by Alan-Qin** [comment]
Hello George, I apologize for my delayed response. 
This is the source model.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/43122728/226384757-0ad918e2-a89b-4b12-8ba4-eb59ccfacfa0.png">
These are victim models.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/43122728/226385718-0e05c7a8-3ae8-47cf-b847-ca456eea8455.png">

Zeyu

**Comment by GeorgeCarpenter** [comment]
Thanks.
